version: '2'
volumes: 
        nextcloud: 
                driver: local
                driver_opts:
                        o: bind
                        type: none
                        device: /mnt/glacier/nextcloud/nextcloud
        db: 
                driver: local
                driver_opts:
                        o: bind
                        type: none
                        device: /mnt/glacier/nextcloud/db

services:
        db:
                image: mariadb
                container_name: nextcloud_db
                restart: unless-stopped
                command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
                volumes:
                        - db:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=R3birth!
                        - MYSQL_PASSWORD=R3birth!
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
        app:
                image: nextcloud
                container_name: nextcloud
                restart: unless-stopped
                volumes:
                        - nextcloud:/var/www/html
                environment:
                        - MYSQL_PASSWORD=R3birth!
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
                        - MYSQL_HOST=db
networks:
  default:
    name: internal
    external: true
