version: '2'


services:

  #icalserver:
  #  build: .
  #  restart: always
  #  environment:
  #    - WEKAN_HOST=https://wekan.blizzard.systems
  #    - WEKAN_USER=admin
  #    - WEKAN_PASSWORD=admin
  #    - LISTEN_HOST=wekan
  #    - LISTEN_PORT=8091
  #  network_mode: service:wekan


  wekandb:
    image: mongo:5
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: quay.io/wekan/wekan:v6.78
    container_name: wekan-app
    restart: always
    ports:
      - "8091:8091"
        #build:
        #  context: .
        #  dockerfile: Dockerfile
    environment:
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=https://wekan.blizzard.systems
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan.blizzardfinnegan@gmail.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw


volumes:
  wekan-files:
    driver: local
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  default:
    name: internal
    external: true
